gems:

repositories:
  remote:
    - http://repo1.maven.org/maven2

artifacts:
  simpleweb: org.simpleframework:simple:jar:4.1.21

  # -- test dependencies
  jmock: org.jmock:jmock:jar:2.5.1
  cglib: cglib:cglib-nodep:jar:2.1_3
  objenesis: org.objenesis:objenesis:jar:1.0
  jmock_legacy: org.jmock:jmock-legacy:jar:2.5.1
  hamcrest: org.hamcrest:hamcrest-all:jar:1.3
  juniversalchardet: com.googlecode.juniversalchardet:juniversalchardet:jar:1.0.3
  htmlunit: net.sourceforge.htmlunit:htmlunit:jar:2.9

junit: 4.11
jmock: 2.5.1
