gems:

repositories:
  remote:
    - http://repo1.maven.org/maven2

artifacts:
  simple: org.simpleframework:simple:jar:5.1.6
  mustache: com.samskivert:jmustache:jar:1.9

  # -- test dependencies
  jmock: org.jmock:jmock:jar:2.6.0
  cglib: cglib:cglib-nodep:jar:2.1_3
  objenesis: org.objenesis:objenesis:jar:1.0
  jmock_legacy: org.jmock:jmock-legacy:jar:2.6.0
  hamcrest: org.hamcrest:hamcrest-all:jar:1.3
  juniversalchardet: com.googlecode.juniversalchardet:juniversalchardet:jar:1.0.3
  htmlunit: net.sourceforge.htmlunit:htmlunit:jar:2.14

junit: 4.11
jmock: 2.6.0